version: "3.8"

services:
  db:
    image: postgres:13.10
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    container_name: backend
    build: .
    env_file:
      - .env
    restart: always
    depends_on:
      - db
    ports:
      - "8086:8086"
    logging:
      options:
        max-size: 10m

volumes:
  pg_data_production: